### ISSUE TITLE
Still alive

### ISSUE THREAD

**Issue by isaactzab** [TeamNewPipe/PipeCast#2]
please send a sign of life. I have also been waiting for a manual how to test this project. I would like to collaborate but I do not know where to start.

**Comment by ghost** [comment]
> please send a sign of life.

I'm alive, but I've been really busy with other things recently. I hope I
can work on it this weekend.

> I have also been waiting for a manual how to test this project.

It only supports discovering UPnP A/V MediaRenderers at the moment (and
only if your PC's IP address is 192.168.1.124, because I hardcoded it,
since I couldn't find a reliable method for getting the IP address, but now
I've found one, so that's the first thing I'll fix), so there's not really
anything to test right now.

> I would like to collaborate but I do not know where to start.

Well, you need at least 2 PCs in a network that supports UDP multicast (it
can also be 2 VMs and a virtual network). On one of them you need a Java
IDE with Gradle support, like Android Studio, IntelliJ IDEA or Eclipse. On
the other one, you need GMRender-Ressurect. In your IDE you could import
PipeCast and create a new Gradle Java application where you include
PipeCast and use
`org.schabi.newpipe.cast.protocols.upnp.UpnpDiscoverer#discoverDevices` to
discover UPnP A/V MediaRenderers, like the one you're running on the other
PC.

**Comment by isaactzab** [comment]
Thank you for your fast response! I will try to test it. 
Regards,
